version: '3.8'

services:
  api:
    build:
      context: .
      # target: development
    volumes:
      - ./:/app
      - /app/node_modules
    command: npx nest start --debug --watch
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vault_x
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:alpine
    platform: linux/arm64 # Explicitly specify platform

    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  pgadmin_data:
  redis-data:
